fix: ignore exit code 1 when GITHUB_TOKEN is not present
github runs shell script with -e and therefore all commands should
succeed unless encounter an error

otherwise GitHub is showing:

```
Error: Process completed with exit code 1.
```